### PR TITLE
Update godot-cpp & add a more accessible scons command to readme

### PR DESCRIPTION
**Pull request by krazyjakee**
This version fixes a crash with Godot 4 RC1

### CODE REVIEW

**Comment by codecat** [comment]
Which crash does it fix exactly? I already pushed the changes needed for RC1. Was there another crash?

**Comment by somebody1121** [comment]
Maybe it's because of this: https://github.com/godotengine/godot/pull/72926

That or because the version from the assets library it's still on 0.14

**Comment by codecat** [comment]
Yeah, but I don't see why that would cause a crash.

**Comment by somebody1121** [comment]
Then more likely it's the outdated version of the assets library

**Comment by krazyjakee** [comment]
Sorry I'm late to the party. Could well be that you beat me to it @codecat . I could repurpose this PR to make the readme changes if you prefer?

**Comment by codecat** [comment]
Definitely, if you can update the PR that'd be great!

**Comment by krazyjakee** [comment]
I'll sort the readme in another PR at a later date

**Pull request closed without merging**
