### PR TITLE
Make godot-tbloader use the new FileAccess class instead of File

### PR DESCRIPTION
**Pull request by EIREXE**

### CODE REVIEW

**Comment by codecat** [comment]
Is this still compatible with Beta 1? This change looks very recent on the master branch.

**Comment by EIREXE** [comment]
> Is this still compatible with Beta 1? This change looks very recent on the master branch.

No, it isn't, it's tracking master

**Comment by codecat** [comment]
Yeah, I'll wait a bit with merging this PR then. Maybe we need a `develop` branch for the Godot master branch 🤔

**Comment by codecat** [comment]
This has to be rebased on master after e22ae9aa354ba01b36f36d841bb90290b9d97b8a.

**Comment by codecat** [comment]
Thanks for the PR! 🎉

**Pull request merged**
